import { Roboto } from "next/font/google";
import "./globals.scss";
import ThemeProvider from "@/component/darkMode/ThemeContext";
import NavBar from "@/component/NavBar/NavBar";

const inter = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='clr'>
      <body className={inter.className}>
        <ThemeProvider>
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
